service: simple-crud

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  iam:
    role: ${opt:aws_role_arn}
  stackTags:
    slsApp: simple-crud

plugins:
  - serverless-webpack
  - serverless-prune-plugin

functions:
  create: ${file(src/functions/create/function.yml):create}
  delete: ${file(src/functions/delete/function.yml):delete}
  get: ${file(src/functions/get/function.yml):get}
  update: ${file(src/functions/update/function.yml):update}

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
  prune:
    automatic: true
    number: 2

package:
  individually: true

resources:
  - ${file(src/resources/dynamodb.yml)}
# TODO
# SEARCH AND REPLACE THE FOLLOWING:
# 1. service property in this file (simple-crud)
# 2. Table name in resources/dynamodb.yml (SimpleCrudTable)
