service: sls-template # refactor

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  iam:
    role: ${opt:aws_role_arn}
  stackTags:
    slsTemplate: value1 # refactor

plugins:
  - serverless-webpack
  - serverless-prune-plugin

functions:
  create: ${file(src/functions/create/function.yml):create}
  # get: ${file(src/functions/get/function.yml):get}
  # delete: ${file(src/functions/delete/function.yml):delete}

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
  prune:
    automatic: true
    number: 2

package:
  individually: true
# resources:
#   - ${file(src/resources/dynamodb.yml)}
